export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REGISTER: '/auth/register',
    ME: '/auth/me',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    USER_INFO: '/userinfo',
  },
  ADMINS: {
    LIST: '/admins',
    CREATE: '/admins',
    GET: (id: string) => `/admins/${id}`,
    UPDATE: (id: string) => `/admins/${id}`,
    DELETE: (id: string) => `/admins/${id}`,
    LOGIN: '/admins/login',
    LOGOUT: '/admins/logout',
    ME: '/admins/me',
    REFRESH_TOKEN: '/admins/refresh-token',
    FORGOT_PASSWORD: '/admins/forgot-password',
    RESET_PASSWORD: '/admins/reset-password',
  },
  USERS: {
    LIST: '/users',
    CREATE: '/users',
    GET: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    ALL: '/users/all',
  },
  MEDIA: {
    LIST: '/media',
    CREATE: '/media',
    GET: (id: string) => `/media/${id}`,
    UPDATE: (id: string) => `/media/${id}`,
    DELETE: (id: string) => `/media/${id}`,
  },
  MARKET_REPORTS: {
    LIST: '/market-reports',
    CREATE: '/market-reports',
    GET: (id: string) => `/market-reports/${id}`,
    UPDATE: (id: string) => `/market-reports/${id}`,
    DELETE: (id: string) => `/market-reports/${id}`,
    SUBMIT: (id: string) => `/market-reports/${id}/submit`,
    UPDATE_SECTION: (id: string, key: string) => `/market-reports/${id}/sections/${key}`,
    UPDATE_SUBSECTION: (id: string, sectionKey: string, subsectionKey: string) =>
      `/market-reports/${id}/sections/${sectionKey}/subsections/${subsectionKey}`,
    REGENERATE: (id: string) => `/market-reports/${id}/regenerate/`,
    REGENERATE_SUBSECTION: (id: string) => `/market-reports/${id}/regenerateSubsection`,
  },
  NBC_PAPERS: {
    LIST: '/nbc-papers',
    CREATE: '/nbc-papers',
    GET: (id: string) => `/nbc-papers/${id}`,
    UPDATE: (id: string) => `/nbc-papers/${id}`,
    DELETE: (id: string) => `/nbc-papers/${id}`,
    SUBMIT: (id: string) => `/nbc-papers/${id}/submit`,
    UPDATE_SECTION: (id: string, key: string) => `/nbc-papers/${id}/sections/${key}`,
    UPDATE_SUBSECTION: (id: string, sectionKey: string, subsectionKey: string) =>
      `/nbc-papers/${id}/sections/${sectionKey}/subsections/${subsectionKey}`,
    REGENERATE: (id: string) => `/nbc-papers/${id}/regenerate`,
    REGENERATE_SUBSECTION: (id: string) => `/nbc-papers/${id}/regenerateSubsection`,
  },
  HISTORY: {
    LIST: '/history',
    CREATE: '/history',
    GET: (id: string) => `/history/${id}`,
    UPDATE: (id: string) => `/history/${id}`,
    DELETE: (id: string) => `/history/${id}`,
  },
  PAPERS: {
    LIST: '/papers',
    CREATE: '/papers',
    GET: (id: string) => `/papers/${id}`,
    UPDATE: (id: string) => `/papers/${id}`,
    DELETE: (id: string) => `/papers/${id}`,
  },
  PAYLOAD_KV: {
    LIST: '/payload-kv',
    CREATE: '/payload-kv',
    GET: (id: string) => `/payload-kv/${id}`,
    UPDATE: (id: string) => `/payload-kv/${id}`,
    DELETE: (id: string) => `/payload-kv/${id}`,
  },
  PAYLOAD_LOCKED_DOCUMENTS: {
    LIST: '/payload-locked-documents',
    CREATE: '/payload-locked-documents',
    GET: (id: string) => `/payload-locked-documents/${id}`,
    UPDATE: (id: string) => `/payload-locked-documents/${id}`,
    DELETE: (id: string) => `/payload-locked-documents/${id}`,
  },
  PAYLOAD_PREFERENCES: {
    LIST: '/payload-preferences',
    CREATE: '/payload-preferences',
    GET: (id: string) => `/payload-preferences/${id}`,
    UPDATE: (id: string) => `/payload-preferences/${id}`,
    DELETE: (id: string) => `/payload-preferences/${id}`,
  },
  PAYLOAD_MIGRATIONS: {
    LIST: '/payload-migrations',
    CREATE: '/payload-migrations',
    GET: (id: string) => `/payload-migrations/${id}`,
    UPDATE: (id: string) => `/payload-migrations/${id}`,
    DELETE: (id: string) => `/payload-migrations/${id}`,
  },
  COMPANY_STATS: {
    GET: (userId: string) => `/company_stats/${userId}`,
  },
  PAPER_TYPES: {
    LIST: '/paper_types',
  },
  DOCUMENT_TEMPLATES: {
    LIST: '/document_templates',
    CREATE: '/document_templates',
    GET: (id: string) => `/document_templates/${id}`,
    UPDATE: (id: string) => `/document_templates/${id}`,
    DELETE: (id: string) => `/document_templates/${id}`,
  },
  DOCUMENTS: {
    LIST: '/documents',
    CREATE: '/documents',
    GET: (id: string) => `/documents/${id}`,
    UPDATE: (id: string) => `/documents/${id}`,
    DELETE: (id: string) => `/documents/${id}`,
  },
};
